[project]
name = "u2fold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Frankwii", email = "frank.william.hammond@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
u2fold = "u2fold:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
